Fix build and pipelines (#50)
- Add VERSION file and unify the way of getting version string in the
  build scripts.
- Rewrite all pipelines.
- pljava_xxx_1.out files have been removed since they are not being used
  by anyone.
- pljava_test_optimizer.out has been removed. Since even when orca is
  enabled, the error message is the same as the planner:

< ERROR:  function cannot execute on a QE slice because it accesses relation "javatest.employees1"
< CONTEXT:  SQL statement "SELECT id, name, salary FROM employees1 WHERE salary > $1"
---
> ERROR:  query plan with multiple segworker groups is not supported
> HINT:  likely caused by a function that reads or modifies data in a distributed table